create table movies (
  id bigint generated by default as identity primary key,
  name text,
  description text
);

alter table movies enable row level security;

-- READ: Allow users to see all movies
create policy "Allow select for authenticated users"
on public.movies for select
to authenticated
using (true);

-- INSERT: Allow users to add new movies
create policy "Allow insert for authenticated users"
on public.movies for insert
to authenticated
with check (true);

-- UPDATE: Allow users to edit any movie
create policy "Allow update for authenticated users"
on public.movies for update
to authenticated
using (true)
with check (true);

-- DELETE: Allow users to remove any movie
create policy "Allow delete for authenticated users"
on public.movies for delete
to authenticated
using (true);



-- public.users table

create table public.users (
  id uuid references auth.users on delete cascade primary key,
  email text,
  display_name text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

-- READ: Allow authenticated users to view all user profiles
create policy "Users can select" 
on public.users for select 
to authenticated 
using ((select auth.uid()) = id);

-- INSERT: Allow users to insert only their own profile
create policy "Users can insert" 
on public.users for insert 
to authenticated 
with check ((select auth.uid()) = id);

-- UPDATE: Allow users to update only their own profile
create policy "Users can update" 
on public.users for update 
to authenticated 
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- DELETE: Allow users to delete only their own profile
create policy "Users can delete" 
on public.users for delete 
to authenticated 
using ((select auth.uid()) = id);


-- Trigger function 

create or replace function public.handle_new_user()
returns trigger 
language plpgsql 
security definer 
set search_path = ''
as $$
begin
  insert into public.users (id, email, display_name)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'display_name'
  );
  return new;
end;
$$;

-- Drop and recreate the trigger
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();