create table movies (
  id bigint generated by default as identity primary key,
  name text,
  description text
);

alter table movies enable row level security;

-- READ: Allow users to see all movies
create policy "Allow select for authenticated users"
on public.movies for select
to authenticated
using (true);

-- INSERT: Allow users to add new movies
create policy "Allow insert for authenticated users"
on public.movies for insert
to authenticated
with check (true);

-- UPDATE: Allow users to edit any movie
create policy "Allow update for authenticated users"
on public.movies for update
to authenticated
using (true)
with check (true);

-- DELETE: Allow users to remove any movie
create policy "Allow delete for authenticated users"
on public.movies for delete
to authenticated
using (true);